import { absoluteUrl } from '@ilham/seo';
import { sitemapFamilies } from '../sitemap';

/**
 * Sitemap index — the single URL to submit to Search Console / Bing. It lists the per-family
 * shards (`/sitemap/<family>.xml`, generated by app/sitemap.ts). Next reserves `/sitemap.xml`
 * for that metadata route, hence the `/sitemap-index.xml` path; robots.txt lists both.
 */
export const revalidate = 3600;

export function GET() {
  const items = sitemapFamilies
    .map((family) => `<sitemap><loc>${absoluteUrl(`/sitemap/${family}.xml`)}</loc></sitemap>`)
    .join('');
  const xml = `<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${items}</sitemapindex>`;
  return new Response(xml, {
    headers: {
      'content-type': 'application/xml; charset=utf-8',
      'cache-control': 'public, max-age=3600',
    },
  });
}
